export const questionText6 = [
	"In this blotter I would like you to tell me what the column title the “Unset” values apply to."
];

export interface ExampleRow6 {
	strategyType: string,
	cmdStatus: string,
	symbol: string,
	user: string,
	progress: string,
	alogstate: string,
	"$": string,
	"δ": string,
	"$": string,
	"δ": string,
	"$": string,
	"δ": string,
}

export const exampleRows6 = [
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "AMD",
		user: "awills",
		progress: "52%",
		alogstate: "Running",
		"$": "-1,891",
		"δ": "",
		"$": "2390",
		"δ": "4.73",
		"$": "-624",
		"δ": "-12",
	},
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "AMD",
		user: "awills",
		progress: "58%",
		alogstate: "Running",
		"$": "155",
		"δ": "",
		"$": "-3,741",
		"δ": "-27",
		"$": "-3,250",
		"δ": "-23",
	},
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "AMD",
		user: "awills",
		progress: "100%",
		alogstate: "Complete",
		"$": "-1.265",
		"δ": "",
		"$": "-1,349",
		"δ": "-8.4",
		"$": "-1,988",
		"δ": "-12",
	},
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "AMZN",
		user: "awills",
		progress: "5%",
		alogstate: "Running",
		"$": "-378",
		"δ": "",
		"$": "113",
		"δ": "6.63",
		"$": "-190",
		"δ": "-11.3",
	},
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "AMZN",
		user: "awills",
		progress: "72%",
		alogstate: "Running",
		"$": "0",
		"δ": "",
		"$": "356",
		"δ": "1.99",
		"$": "767",
		"δ": "4.2",
	},
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "AMZN",
		user: "awills",
		progress: "0%",
		alogstate: "Running",
		"$": "0",
		"δ": "",
		"$": "0",
		"δ": "0",
		"$": "0",
		"δ": "0",
	},
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "BA",
		user: "awills",
		progress: "0%",
		alogstate: "Cancelled",
		"$": "0",
		"δ": "",
		"$": "0",
		"δ": "0",
		"$": "0",
		"δ": "0",
	},
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "BRZB",
		user: "awills",
		progress: "10%",
		alogstate: "Running",
		"$": "-260",
		"δ": "",
		"$": "0",
		"δ": "0",
		"$": "126",
		"δ": "14.7",
	},
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "BABA",
		user: "awills",
		progress: "33%",
		alogstate: "Running",
		"$": "-1,289",
		"δ": "",
		"$": "177",
		"δ": "3.5",
		"$": "83",
		"δ": "1.63",
	},
	{
		strategyType: "SingleLeg",
		cmdStatus: "Unset",
		symbol: "BAC",
		user: "awills",
		progress: "44%",
		alogstate: "Running",
		"$": "-374",
		"δ": "",
		"$": "56.3",
		"δ": "3.44",
		"$": "-124",
		"δ": "-7.6",
	},
];